export default {
    BROKER_DISCONNECTED: 0,
    BROKER_CONNECT_ERROR: 1,
    BROKER_RECONNECT_ATTEMPT_ERROR: 2,
    BROKER_RECONNECT_FATAL_ERROR: 3,
    BROKER_INVALID_CONNECTION_ERROR: 4,
    TOPIC_GET_ERROR: 5,
    TOPIC_SUBSCRIBE_ERROR: 6,
    TOPIC_STREAM_OUT_OF_ORDER: 7
}
